//! Types for passing adopted track information from a parent grid to a subgrid,
//! and for hoisting the items of a subgrid into an ancestor grid's track sizing.
//! See <https://www.w3.org/TR/css-grid-2/#subgrids>
use super::explicit_grid::{compute_explicit_grid_size_in_axis, AutoRepeatStrategy};
use super::implicit_grid::compute_grid_size_estimate;
use super::placement::place_grid_items;
use super::types::{CellOccupancyMatrix, GridItem, GridTrack, GridTrackKind, NamedLineResolver, TrackCounts};
use super::OriginZeroLine;
use crate::geometry::{AbsoluteAxis, AbstractAxis, InBothAbsAxis, Line, Rect, Size};
use crate::style::{AlignItems, AlignSelf, BoxGenerationMode, Position};
use crate::style_helpers::{FromLength, TaffyZero};
use crate::sys::f32_max;
use crate::tree::{LayoutGridContainer, LayoutPartialTreeExt, NodeId};
use crate::util::sys::Vec;
use crate::util::ResolveOrZero;
use crate::{CoreStyle, GridContainerStyle, LengthPercentage, MaxTrackSizingFunction, MinTrackSizingFunction};

/// The sizes of the tracks that a subgrid adopts from its parent grid in one axis.
///
/// Sizes are in the subgrid's own coordinate space: the sizes of the first and last track
/// are reduced by the subgrid's margins (the subgrid's own border and padding are subtracted
/// by the subgrid itself when it lays itself out).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct AdoptedTracks {
    /// The used sizes of the adopted tracks (in order)
    pub track_sizes: Vec<f32>,
    /// The used sizes of the gutters *between* the adopted tracks
    /// (length = `track_sizes.len() - 1`)
    pub gutter_sizes: Vec<f32>,
}

impl AdoptedTracks {
    /// Construct `AdoptedTracks` from the slice of the parent grid's tracks covered by the
    /// subgrid's grid area (excluding the bounding lines). Such a slice always has the form
    /// `[Track, Gutter, Track, ..., Track]`.
    ///
    /// `start_reduction`/`end_reduction` are subtracted from the first/last track respectively
    /// (used to account for the subgrid's own margins).
    pub(super) fn from_track_range(tracks: &[GridTrack], start_reduction: f32, end_reduction: f32) -> Self {
        let mut track_sizes = Vec::with_capacity(tracks.len() / 2 + 1);
        let mut gutter_sizes = Vec::with_capacity(tracks.len() / 2);
        for track in tracks {
            match track.kind {
                GridTrackKind::Track => track_sizes.push(track.base_size),
                // Note: `content_alignment_adjustment` accounts for additional spacing between
                // tracks generated by the parent's align-content/justify-content property
                GridTrackKind::Gutter => gutter_sizes.push(track.base_size + track.content_alignment_adjustment),
            }
        }
        let track_count = track_sizes.len();
        if track_count > 0 {
            track_sizes[0] = f32_max(track_sizes[0] - start_reduction, 0.0);
            track_sizes[track_count - 1] = f32_max(track_sizes[track_count - 1] - end_reduction, 0.0);
        }
        Self { track_sizes, gutter_sizes }
    }

    /// The number of adopted tracks
    #[inline(always)]
    pub fn track_count(&self) -> usize {
        self.track_sizes.len()
    }
}

/// Track information passed down from a parent grid when laying out a subgrid
/// (a grid container which is itself a grid item and has `grid-template-rows` and/or
/// `grid-template-columns` set to `subgrid`).
///
/// An axis which is `None` indicates that no tracks are being passed down in that axis
/// (either because the child is not subgridded in that axis, or because the parent doesn't
/// support passing them down). A subgridded axis with no adopted tracks available behaves
/// as if its template were `none`.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct SubgridContext {
    /// Adopted column tracks (if the child is subgridded in the column/inline axis)
    pub columns: Option<AdoptedTracks>,
    /// Adopted row tracks (if the child is subgridded in the row/block axis)
    pub rows: Option<AdoptedTracks>,
}

impl SubgridContext {
    /// Build the `SubgridContext` for a grid item using the parent's current track sizes.
    /// Returns `None` if the item is not subgridded in either axis.
    ///
    /// `margins` should be the item's resolved margins: these reduce the size of the first/last
    /// adopted track as seen by the subgrid (its border box excludes its margins).
    pub(super) fn for_item(
        item: &GridItem,
        columns: &[GridTrack],
        rows: &[GridTrack],
        margins: crate::geometry::Rect<f32>,
    ) -> Option<Self> {
        if !item.subgridded_axes.horizontal && !item.subgridded_axes.vertical {
            return None;
        }
        Some(SubgridContext {
            columns: item.subgridded_axes.horizontal.then(|| {
                AdoptedTracks::from_track_range(
                    &columns[item.track_range_excluding_lines(AbstractAxis::Inline)],
                    margins.left,
                    margins.right,
                )
            }),
            rows: item.subgridded_axes.vertical.then(|| {
                AdoptedTracks::from_track_range(
                    &rows[item.track_range_excluding_lines(AbstractAxis::Block)],
                    margins.top,
                    margins.bottom,
                )
            }),
        })
    }
}

/// Initialize the track vector of a subgridded axis from the tracks adopted from the parent
/// grid. The adopted tracks have fixed sizes and do not participate in track sizing.
///
/// `start_reduction`/`end_reduction` are subtracted from the first/last track respectively
/// and should be set to the subgrid's own border+padding (+scrollbar gutter) so that track
/// boundaries remain fixed relative to the subgrid's grid area in the parent.
pub(super) fn initialize_subgridded_tracks(
    tracks: &mut Vec<GridTrack>,
    adopted: &AdoptedTracks,
    start_reduction: f32,
    end_reduction: f32,
) {
    let track_count = adopted.track_count();

    tracks.clear();
    tracks.reserve(track_count * 2 + 1);
    tracks.push(GridTrack::gutter(LengthPercentage::ZERO));

    for (index, size) in adopted.track_sizes.iter().enumerate() {
        let mut size = *size;
        if index == 0 {
            size = f32_max(size - start_reduction, 0.0);
        }
        if index == track_count - 1 {
            size = f32_max(size - end_reduction, 0.0);
        }

        let mut track =
            GridTrack::new(MinTrackSizingFunction::from_length(size), MaxTrackSizingFunction::from_length(size));
        track.base_size = size;
        track.growth_limit = size;
        tracks.push(track);

        let gutter_size =
            if index < track_count - 1 { adopted.gutter_sizes.get(index).copied().unwrap_or(0.0) } else { 0.0 };
        let mut gutter = GridTrack::gutter(LengthPercentage::from_length(gutter_size));
        gutter.base_size = gutter_size;
        gutter.growth_limit = gutter_size;
        tracks.push(gutter);
    }

    // Mark first and last grid lines as collapsed
    tracks.first_mut().unwrap().collapse();
    tracks.last_mut().unwrap().collapse();
}

/// For each item of this grid which is a subgrid, recursively collect the subgrid's own items
/// (and the items of any nested subgrids) and append them to this grid's item list as "hoisted"
/// items so that they participate in this grid's track sizing in the subgridded axes.
/// See <https://www.w3.org/TR/css-grid-2/#subgrid-sizing>
///
/// This must be called after this grid's own items have been placed (and their `subgridded_axes`
/// resolved) but before track sizing. Hoisted items must be removed from the item list (see
/// [`GridItem::is_hoisted`]) before final item positioning.
pub(super) fn hoist_subgrid_items<Tree: LayoutGridContainer>(
    tree: &Tree,
    items: &mut Vec<GridItem>,
    inner_node_size: Size<Option<f32>>,
) {
    /// Info about a subgrid whose items should be hoisted
    struct SubgridInfo {
        /// The subgrid's node id
        node: NodeId,
        /// For each axis which is subgridded all the way up to the grid doing the hoisting:
        /// the subgrid's placement in that grid's origin-zero coordinates
        chained: InBothAbsAxis<Option<Line<OriginZeroLine>>>,
        /// The subgrid's placement in the hoisting grid's origin-zero coordinates. Used as the
        /// placement of hoisted items in non-chained axes (where their internal placement within
        /// the subgrid is not meaningful to the hoisting grid).
        fallback_placement: InBothAbsAxis<Line<OriginZeroLine>>,
        /// Margin/border/padding of ancestor subgrids which applies to items placed at this
        /// subgrid's edges (per side)
        accumulated_mbp: Rect<f32>,
    }

    let subgrids: Vec<SubgridInfo> = items
        .iter()
        .filter(|item| item.is_subgrid())
        .map(|item| SubgridInfo {
            node: item.node,
            chained: InBothAbsAxis {
                horizontal: item.subgridded_axes.horizontal.then_some(item.column),
                vertical: item.subgridded_axes.vertical.then_some(item.row),
            },
            fallback_placement: InBothAbsAxis { horizontal: item.column, vertical: item.row },
            accumulated_mbp: Rect::ZERO,
        })
        .collect();

    for subgrid in subgrids {
        hoist_items_from_subgrid(tree, items, &subgrid, inner_node_size);
    }

    #[allow(clippy::too_many_arguments)]
    fn hoist_items_from_subgrid<Tree: LayoutGridContainer>(
        tree: &Tree,
        items: &mut Vec<GridItem>,
        subgrid: &SubgridInfo,
        inner_node_size: Size<Option<f32>>,
    ) {
        if tree.child_count(subgrid.node) == 0 {
            return;
        }

        let style = tree.get_grid_container_style(subgrid.node);
        let direction = style.direction();
        let grid_auto_flow = style.grid_auto_flow();
        let align_items = style.align_items().unwrap_or(AlignItems::STRETCH);
        let justify_items = style.justify_items().unwrap_or(AlignItems::STRETCH);

        // Resolve the subgrid's margin/border/padding. This is applied as an extra layer of
        // margin to hoisted items placed in the subgrid's first/last track.
        // Note: percentages resolve against the hoisting grid's inner width as an approximation.
        let margin = style.margin().resolve_or_zero(inner_node_size.width, |val, basis| tree.calc(val, basis));
        let padding = style.padding().resolve_or_zero(inner_node_size.width, |val, basis| tree.calc(val, basis));
        let border = style.border().resolve_or_zero(inner_node_size.width, |val, basis| tree.calc(val, basis));
        let mbp = margin + padding + border;

        // Compute the number of explicit tracks in each axis. In a chained (subgridded) axis this
        // is the number of adopted tracks. In a non-chained axis it is resolved from the subgrid's
        // own template (note: the container size is unknown at this point, so auto-repetitions
        // resolve to a single repetition).
        let (col_auto_repetitions, template_col_count) = match subgrid.chained.horizontal {
            Some(placement) => (0, placement.span()),
            None => compute_explicit_grid_size_in_axis(
                &style,
                None,
                AutoRepeatStrategy::MaxRepetitionsThatDoNotOverflow,
                |val, basis| tree.calc(val, basis),
                AbsoluteAxis::Horizontal,
            ),
        };
        let (row_auto_repetitions, template_row_count) = match subgrid.chained.vertical {
            Some(placement) => (0, placement.span()),
            None => compute_explicit_grid_size_in_axis(
                &style,
                None,
                AutoRepeatStrategy::MaxRepetitionsThatDoNotOverflow,
                |val, basis| tree.calc(val, basis),
                AbsoluteAxis::Vertical,
            ),
        };

        let mut name_resolver = NamedLineResolver::new(&style, col_auto_repetitions, row_auto_repetitions);
        let explicit_col_count = if subgrid.chained.horizontal.is_some() {
            template_col_count
        } else {
            template_col_count.max(name_resolver.area_column_count())
        };
        let explicit_row_count = if subgrid.chained.vertical.is_some() {
            template_row_count
        } else {
            template_row_count.max(name_resolver.area_row_count())
        };
        name_resolver.set_explicit_column_count(explicit_col_count);
        name_resolver.set_explicit_row_count(explicit_row_count);

        // Estimate track counts and place the subgrid's items (within the subgrid's own
        // coordinate space). Chained axes have no implicit tracks: placements are clamped.
        let child_styles_iter = tree.child_ids(subgrid.node).map(|child| tree.get_grid_child_style(child));
        let (mut est_col_counts, mut est_row_counts) =
            compute_grid_size_estimate(explicit_col_count, explicit_row_count, direction, child_styles_iter);
        if subgrid.chained.horizontal.is_some() {
            est_col_counts = TrackCounts::from_raw(0, explicit_col_count, 0);
        }
        if subgrid.chained.vertical.is_some() {
            est_row_counts = TrackCounts::from_raw(0, explicit_row_count, 0);
        }

        let mut sub_items: Vec<GridItem> = Vec::with_capacity(tree.child_count(subgrid.node));
        let mut cell_occupancy_matrix = CellOccupancyMatrix::with_track_counts(est_col_counts, est_row_counts);
        let in_flow_children_iter = || {
            tree.child_ids(subgrid.node)
                .enumerate()
                .map(|(index, child_node)| (index, child_node, tree.get_grid_child_style(child_node)))
                .filter(|(_, _, style)| {
                    style.box_generation_mode() != BoxGenerationMode::None && style.position() != Position::Absolute
                })
        };
        place_grid_items(
            &mut cell_occupancy_matrix,
            &mut sub_items,
            in_flow_children_iter,
            direction,
            grid_auto_flow,
            align_items,
            justify_items,
            &name_resolver,
            InBothAbsAxis {
                horizontal: subgrid.chained.horizontal.map(|_| explicit_col_count),
                vertical: subgrid.chained.vertical.map(|_| explicit_row_count),
            },
        );
        drop(style);

        for mut sub_item in sub_items {
            let mut extra_margin = Rect::ZERO;

            // Detect whether the item is a nested subgrid, and if so which of its axes chain
            // through to the hoisting grid
            let sub_item_style = tree.get_grid_child_style(sub_item.node);
            let nested_subgridded_axes = if sub_item_style.is_grid_container() {
                drop(sub_item_style);
                let container_style = tree.get_grid_container_style(sub_item.node);
                InBothAbsAxis {
                    horizontal: subgrid.chained.horizontal.is_some()
                        && container_style.is_subgridded(AbsoluteAxis::Horizontal),
                    vertical: subgrid.chained.vertical.is_some()
                        && container_style.is_subgridded(AbsoluteAxis::Vertical),
                }
            } else {
                drop(sub_item_style);
                InBothAbsAxis { horizontal: false, vertical: false }
            };

            // Translate the item's placement in chained axes into the hoisting grid's origin-zero
            // coordinates, applying the subgrid's mbp as extra margin to items in edge tracks.
            // In non-chained axes fall back to the subgrid's own placement.
            match subgrid.chained.horizontal {
                Some(outer_placement) => {
                    if sub_item.column.start.0 == 0 {
                        extra_margin.left = mbp.left + subgrid.accumulated_mbp.left;
                    }
                    if sub_item.column.end.0 == explicit_col_count as i16 {
                        extra_margin.right = mbp.right + subgrid.accumulated_mbp.right;
                    }
                    sub_item.column = Line {
                        start: OriginZeroLine(outer_placement.start.0 + sub_item.column.start.0),
                        end: OriginZeroLine(outer_placement.start.0 + sub_item.column.end.0),
                    };
                }
                None => sub_item.column = subgrid.fallback_placement.horizontal,
            }
            match subgrid.chained.vertical {
                Some(outer_placement) => {
                    if sub_item.row.start.0 == 0 {
                        extra_margin.top = mbp.top + subgrid.accumulated_mbp.top;
                    }
                    if sub_item.row.end.0 == explicit_row_count as i16 {
                        extra_margin.bottom = mbp.bottom + subgrid.accumulated_mbp.bottom;
                    }
                    sub_item.row = Line {
                        start: OriginZeroLine(outer_placement.start.0 + sub_item.row.start.0),
                        end: OriginZeroLine(outer_placement.start.0 + sub_item.row.end.0),
                    };
                }
                None => sub_item.row = subgrid.fallback_placement.vertical,
            }

            sub_item.is_hoisted = true;
            sub_item.extra_margin = extra_margin;
            // Hoisted items participate in sizing only in chained axes; nested subgrids do not
            // participate in axes in which they are themselves subgridded (their own hoisted
            // items participate in their stead)
            sub_item.sizing_participation = InBothAbsAxis {
                horizontal: subgrid.chained.horizontal.is_some() && !nested_subgridded_axes.horizontal,
                vertical: subgrid.chained.vertical.is_some() && !nested_subgridded_axes.vertical,
            };
            // TODO: support baseline alignment of hoisted subgrid items
            if sub_item.align_self == AlignSelf::BASELINE {
                sub_item.align_self = AlignSelf::START;
            }

            // Recursively hoist the items of nested subgrids
            if nested_subgridded_axes.horizontal || nested_subgridded_axes.vertical {
                let nested = SubgridInfo {
                    node: sub_item.node,
                    chained: InBothAbsAxis {
                        horizontal: nested_subgridded_axes.horizontal.then_some(sub_item.column),
                        vertical: nested_subgridded_axes.vertical.then_some(sub_item.row),
                    },
                    fallback_placement: InBothAbsAxis { horizontal: sub_item.column, vertical: sub_item.row },
                    accumulated_mbp: Rect {
                        left: extra_margin.left,
                        right: extra_margin.right,
                        top: extra_margin.top,
                        bottom: extra_margin.bottom,
                    },
                };
                hoist_items_from_subgrid(tree, items, &nested, inner_node_size);
            }

            items.push(sub_item);
        }
    }
}
