//! Types for passing adopted track information from a parent grid to a subgrid
//! See <https://www.w3.org/TR/css-grid-2/#subgrids>
use super::types::{GridItem, GridTrack, GridTrackKind};
use crate::geometry::AbstractAxis;
use crate::style_helpers::{FromLength, TaffyZero};
use crate::sys::f32_max;
use crate::util::sys::Vec;
use crate::{LengthPercentage, MaxTrackSizingFunction, MinTrackSizingFunction};

/// The sizes of the tracks that a subgrid adopts from its parent grid in one axis.
///
/// Sizes are in the subgrid's own coordinate space: the sizes of the first and last track
/// are reduced by the subgrid's margins (the subgrid's own border and padding are subtracted
/// by the subgrid itself when it lays itself out).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct AdoptedTracks {
    /// The used sizes of the adopted tracks (in order)
    pub track_sizes: Vec<f32>,
    /// The used sizes of the gutters *between* the adopted tracks
    /// (length = `track_sizes.len() - 1`)
    pub gutter_sizes: Vec<f32>,
}

impl AdoptedTracks {
    /// Construct `AdoptedTracks` from the slice of the parent grid's tracks covered by the
    /// subgrid's grid area (excluding the bounding lines). Such a slice always has the form
    /// `[Track, Gutter, Track, ..., Track]`.
    ///
    /// `start_reduction`/`end_reduction` are subtracted from the first/last track respectively
    /// (used to account for the subgrid's own margins).
    pub(super) fn from_track_range(tracks: &[GridTrack], start_reduction: f32, end_reduction: f32) -> Self {
        let mut track_sizes = Vec::with_capacity(tracks.len() / 2 + 1);
        let mut gutter_sizes = Vec::with_capacity(tracks.len() / 2);
        for track in tracks {
            match track.kind {
                GridTrackKind::Track => track_sizes.push(track.base_size),
                // Note: `content_alignment_adjustment` accounts for additional spacing between
                // tracks generated by the parent's align-content/justify-content property
                GridTrackKind::Gutter => gutter_sizes.push(track.base_size + track.content_alignment_adjustment),
            }
        }
        let track_count = track_sizes.len();
        if track_count > 0 {
            track_sizes[0] = f32_max(track_sizes[0] - start_reduction, 0.0);
            track_sizes[track_count - 1] = f32_max(track_sizes[track_count - 1] - end_reduction, 0.0);
        }
        Self { track_sizes, gutter_sizes }
    }

    /// The number of adopted tracks
    #[inline(always)]
    pub fn track_count(&self) -> usize {
        self.track_sizes.len()
    }
}

/// Track information passed down from a parent grid when laying out a subgrid
/// (a grid container which is itself a grid item and has `grid-template-rows` and/or
/// `grid-template-columns` set to `subgrid`).
///
/// An axis which is `None` indicates that no tracks are being passed down in that axis
/// (either because the child is not subgridded in that axis, or because the parent doesn't
/// support passing them down). A subgridded axis with no adopted tracks available behaves
/// as if its template were `none`.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct SubgridContext {
    /// Adopted column tracks (if the child is subgridded in the column/inline axis)
    pub columns: Option<AdoptedTracks>,
    /// Adopted row tracks (if the child is subgridded in the row/block axis)
    pub rows: Option<AdoptedTracks>,
}

impl SubgridContext {
    /// Build the `SubgridContext` for a grid item using the parent's current track sizes.
    /// Returns `None` if the item is not subgridded in either axis.
    ///
    /// `margins` should be the item's resolved margins: these reduce the size of the first/last
    /// adopted track as seen by the subgrid (its border box excludes its margins).
    pub(super) fn for_item(
        item: &GridItem,
        columns: &[GridTrack],
        rows: &[GridTrack],
        margins: crate::geometry::Rect<f32>,
    ) -> Option<Self> {
        if !item.subgridded_axes.horizontal && !item.subgridded_axes.vertical {
            return None;
        }
        Some(SubgridContext {
            columns: item.subgridded_axes.horizontal.then(|| {
                AdoptedTracks::from_track_range(
                    &columns[item.track_range_excluding_lines(AbstractAxis::Inline)],
                    margins.left,
                    margins.right,
                )
            }),
            rows: item.subgridded_axes.vertical.then(|| {
                AdoptedTracks::from_track_range(
                    &rows[item.track_range_excluding_lines(AbstractAxis::Block)],
                    margins.top,
                    margins.bottom,
                )
            }),
        })
    }
}

/// Initialize the track vector of a subgridded axis from the tracks adopted from the parent
/// grid. The adopted tracks have fixed sizes and do not participate in track sizing.
///
/// `start_reduction`/`end_reduction` are subtracted from the first/last track respectively
/// and should be set to the subgrid's own border+padding (+scrollbar gutter) so that track
/// boundaries remain fixed relative to the subgrid's grid area in the parent.
pub(super) fn initialize_subgridded_tracks(
    tracks: &mut Vec<GridTrack>,
    adopted: &AdoptedTracks,
    start_reduction: f32,
    end_reduction: f32,
) {
    let track_count = adopted.track_count();

    tracks.clear();
    tracks.reserve(track_count * 2 + 1);
    tracks.push(GridTrack::gutter(LengthPercentage::ZERO));

    for (index, size) in adopted.track_sizes.iter().enumerate() {
        let mut size = *size;
        if index == 0 {
            size = f32_max(size - start_reduction, 0.0);
        }
        if index == track_count - 1 {
            size = f32_max(size - end_reduction, 0.0);
        }

        let mut track =
            GridTrack::new(MinTrackSizingFunction::from_length(size), MaxTrackSizingFunction::from_length(size));
        track.base_size = size;
        track.growth_limit = size;
        tracks.push(track);

        let gutter_size =
            if index < track_count - 1 { adopted.gutter_sizes.get(index).copied().unwrap_or(0.0) } else { 0.0 };
        let mut gutter = GridTrack::gutter(LengthPercentage::from_length(gutter_size));
        gutter.base_size = gutter_size;
        gutter.growth_limit = gutter_size;
        tracks.push(gutter);
    }

    // Mark first and last grid lines as collapsed
    tracks.first_mut().unwrap().collapse();
    tracks.last_mut().unwrap().collapse();
}
