language = "c"
cpp_compat = true
documentation_style = "c99"
line_length = 120

[enum]
rename_variants = "QualifiedScreamingSnakeCase"

[export]
include = ["TaffyNodeId"]

[export.rename]
TaffyResult_f32 = "TaffyFloatResult"
TaffyResult_i32 = "TaffyIntResult"
TaffyResult_TaffyNodeId = "TaffyNodeIdResult"
TaffyResult_TaffyDimension = "TaffyDimensionResult"
TaffyResult_TaffyGridPlacement = "TaffyGridPlacementResult"
TaffyResult_TaffyStyleMutRef = "TaffyStyleMutRefResult"

[parse.expand]
crates = ["ctaffy"]

