/*
**********************************************************
**            AUTOGENERATED CLASSES FOR TAFFY           **
**  This code was automatically generated. Do not edit. **
**********************************************************
*/
package com.dioxuslabs.taffy.enums;

public enum AbsoluteAxis {
    HORIZONTAL,
    VERTICAL
    ;

    private final int ordinal;

    AbsoluteAxis() {
        this.ordinal = ordinal();
    }
}
