/*
**********************************************************
**            AUTOGENERATED CLASSES FOR TAFFY           **
**  This code was automatically generated. Do not edit. **
**********************************************************
*/
package com.dioxuslabs.taffy.enums;

public enum AlignItems {
    START,
    END,
    FLEX_START,
    FLEX_END,
    CENTER,
    BASELINE,
    STRETCH
    ;

    private final int ordinal;

    AlignItems() {
        this.ordinal = ordinal();
    }
}
