/*
**********************************************************
**            AUTOGENERATED CLASSES FOR TAFFY           **
**  This code was automatically generated. Do not edit. **
**********************************************************
*/
package com.dioxuslabs.taffy.enums;

public enum AlignContent {
    START,
    END,
    FLEX_START,
    FLEX_END,
    CENTER,
    STRETCH,
    SPACE_BETWEEN,
    SPACE_EVENLY,
    SPACE_AROUND
    ;

    private final int ordinal;

    AlignContent() {
        this.ordinal = ordinal();
    }
}
