/*
**********************************************************
**            AUTOGENERATED CLASSES FOR TAFFY           **
**  This code was automatically generated. Do not edit. **
**********************************************************
*/
package com.dioxuslabs.taffy.enums;

public enum BoxGenerationMode {
    NORMAL,
    NONE
    ;

    private final int ordinal;

    BoxGenerationMode() {
        this.ordinal = ordinal();
    }
}
