/*
**********************************************************
**            AUTOGENERATED CLASSES FOR TAFFY           **
**  This code was automatically generated. Do not edit. **
**********************************************************
*/
package com.dioxuslabs.taffy.enums;

public enum BoxSizing {
    BORDER_BOX,
    CONTENT_BOX
    ;

    private final int ordinal;

    BoxSizing() {
        this.ordinal = ordinal();
    }
}
