/*
**********************************************************
**            AUTOGENERATED CLASSES FOR TAFFY           **
**  This code was automatically generated. Do not edit. **
**********************************************************
*/
package com.dioxuslabs.taffy.enums;

public enum Display {
    BLOCK,
    FLEX,
    GRID,
    NONE
    ;

    private final int ordinal;

    Display() {
        this.ordinal = ordinal();
    }
}
