/*
**********************************************************
**            AUTOGENERATED CLASSES FOR TAFFY           **
**  This code was automatically generated. Do not edit. **
**********************************************************
*/
package com.dioxuslabs.taffy.enums;

public enum FlexDirection {
    ROW,
    COLUMN,
    ROW_REVERSE,
    COLUMN_REVERSE
    ;

    private final int ordinal;

    FlexDirection() {
        this.ordinal = ordinal();
    }
}
