/*
**********************************************************
**            AUTOGENERATED CLASSES FOR TAFFY           **
**  This code was automatically generated. Do not edit. **
**********************************************************
*/
package com.dioxuslabs.taffy.enums;

public enum FlexWrap {
    NO_WRAP,
    WRAP,
    WRAP_REVERSE
    ;

    private final int ordinal;

    FlexWrap() {
        this.ordinal = ordinal();
    }
}
