/*
**********************************************************
**            AUTOGENERATED CLASSES FOR TAFFY           **
**  This code was automatically generated. Do not edit. **
**********************************************************
*/
package com.dioxuslabs.taffy.enums;

public enum GridAutoFlow {
    ROW,
    COLUMN,
    ROW_DENSE,
    COLUMN_DENSE
    ;

    private final int ordinal;

    GridAutoFlow() {
        this.ordinal = ordinal();
    }
}
