/*
**********************************************************
**            AUTOGENERATED CLASSES FOR TAFFY           **
**  This code was automatically generated. Do not edit. **
**********************************************************
*/
package com.dioxuslabs.taffy.enums;

public enum Overflow {
    VISIBLE,
    CLIP,
    HIDDEN,
    SCROLL
    ;

    private final int ordinal;

    Overflow() {
        this.ordinal = ordinal();
    }
}
