/*
**********************************************************
**            AUTOGENERATED CLASSES FOR TAFFY           **
**  This code was automatically generated. Do not edit. **
**********************************************************
*/
package com.dioxuslabs.taffy.enums;

public enum Position {
    RELATIVE,
    ABSOLUTE
    ;

    private final int ordinal;

    Position() {
        this.ordinal = ordinal();
    }
}
