/*
**********************************************************
**            AUTOGENERATED CLASSES FOR TAFFY           **
**  This code was automatically generated. Do not edit. **
**********************************************************
*/
package com.dioxuslabs.taffy.enums;

public enum TextAlign {
    AUTO,
    LEGACY_LEFT,
    LEGACY_RIGHT,
    LEGACY_CENTER
    ;

    private final int ordinal;

    TextAlign() {
        this.ordinal = ordinal();
    }
}
